apiVersion: apps/v1
kind: Deployment
metadata:
  name: AI-kubewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AI-kubewatch
  template:
    metadata:
      labels:
        app: AI-kubewatch
    spec:
      containers:
        - name: AI-kubewatch
          image: your-acr-name.azurecr.io/AI-kubewatch:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000  # Adjust the port based on your application
      imagePullSecrets:
        - name: myregistry.azurecr.io/samples/nginx  # If using Azure Container Registry, replace with your image pull secret
